
Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000
tip : use List Comprehension ds = pd.Series([0,2, 4, 6, 8..... 10000])


In [16]:

import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [17]:

import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)


0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


**Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000 tip : use List Comprehension ds = pd.Series([0,2, 4, 6, 8..... 10000])**

In [18]:
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64



Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [19]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [20]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series. Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]

In [21]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


Write a Pandas program to convert a NumPy array to a Pandas series.

In [22]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


Write a Pandas program to convert a given Series to an array. Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [23]:

import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


Write a Pandas program to sort a given Series. Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [24]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


Write a Pandas program to create a subsets of a given series based on value and condition. Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5

In [25]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [26]:
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable.

In [27]:

import numpy as np
x = np.random.rand(4, 4)
print("Original array: ")
print(x)
y= x[:2, :]
print("First 2 rows of the above array:")
y= x[:2, :]
print(y)
z= x[:, :3]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[0.1085454  0.99724353 0.15926228 0.14370082]
 [0.2702556  0.30766193 0.37631202 0.51064201]
 [0.30398614 0.68744499 0.57076429 0.273202  ]
 [0.79476069 0.18687662 0.59265993 0.53756339]]
First 2 rows of the above array:
[[0.1085454  0.99724353 0.15926228 0.14370082]
 [0.2702556  0.30766193 0.37631202 0.51064201]]
First 3 columns of the above array:
[[0.1085454  0.99724353 0.15926228]
 [0.2702556  0.30766193 0.37631202]
 [0.30398614 0.68744499 0.57076429]
 [0.79476069 0.18687662 0.59265993]]



Write a NumPy program to create a 10x10 array with random values and find the 

In [28]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.31716482 0.8783293  0.27823518 0.77374478 0.0038006  0.5779312
  0.02511515 0.9562265  0.99547191 0.90228839]
 [0.41465906 0.60815261 0.14958804 0.90497446 0.1537004  0.53908065
  0.3666282  0.53082117 0.60730301 0.14194123]
 [0.05875848 0.31105612 0.99800906 0.32971292 0.59381888 0.6006077
  0.982441   0.47131906 0.34510307 0.65755061]
 [0.66404054 0.9498822  0.78378804 0.53621523 0.83298864 0.29693832
  0.33574529 0.84250803 0.45785449 0.60428218]
 [0.09458942 0.72624496 0.11169297 0.81117462 0.60073065 0.8644821
  0.22517119 0.70046753 0.35404359 0.74235915]
 [0.140893   0.31169373 0.56345565 0.97871935 0.88083231 0.03358152
  0.59852684 0.476693   0.79062156 0.43535099]
 [0.70657224 0.34096402 0.06259537 0.35796831 0.45113558 0.06769791
  0.33070562 0.49931162 0.36059345 0.99887013]
 [0.2730137  0.7339261  0.93958905 0.15364409 0.69368916 0.2762682
  0.35244746 0.49716615 0.0627843  0.05798001]
 [0.29010048 0.81716568 0.57968228 0.84480515 0.43233647 0.09866415


Write a NumPy program to generate 8 random integers between 100 and 300

In [29]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[248 159 273 116 254 293 193 275]


Write a NumPy program to create a random integer nos of size 20 and sort it

In [30]:

import numpy as np
x=np.arange(20)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[12 18 13 17  8  0  6 15  2 10 16  9  4 19  1  5 14 11  3  7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
