In [41]:
#Write a Pandas program to create and display a one-dimensional array using series  containing  even numbers upto 10

import pandas as pd
ds = pd.Series([2, 4, 6, 8,10]) 
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64


In [42]:
#Write a Pandas program to convert a Panda module Series to Python list and its type.

import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


In [43]:
"""Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]
"""
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [44]:
#Write a Pandas program to compare the elements of the two Pandas Series.
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [45]:
#Write a Pandas program to convert a dictionary to a Pandas series.
#Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)


Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


In [46]:
#Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50]
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [47]:
#Write a Pandas program to change the data type of the given  Series into numeric
#['100', '200', 'python', '300.12', '400']

import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


In [48]:
# Write a Pandas program to convert a given Series to an array.
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


In [49]:
#Write a Pandas program to sort a given Series.
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


In [50]:
#Write a Pandas program to add some data to an existing Series.

import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


In [51]:
#Write a Pandas program to create a subset of a given series based on value and condition.

import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


In [52]:
#Write a Pandas program to change the order of index of a given series.
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)


Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


In [53]:
#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.

import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


In [54]:
#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [55]:
#Write a NumPy program to generate five random numbers from the normal distribution.
import numpy as np
x = np.random.normal(size=5)
print(x)

[-0.17512266 -0.38201535 -1.04612602 -0.61293235  0.9068153 ]


In [56]:
#Write a NumPy program to generate six random integers between 10 and 30
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[20 11 22 28 21 15]


In [57]:
#Write a NumPy program to create a 3x3x3 array with random values.
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.99552266 0.04309911 0.81168995]
  [0.18084835 0.90481485 0.2917084 ]
  [0.91524284 0.10115516 0.41506466]]

 [[0.67324919 0.22199041 0.21976458]
  [0.42236341 0.85178752 0.1183766 ]
  [0.81355171 0.75957427 0.04742739]]

 [[0.59388766 0.16414797 0.18494002]
  [0.18617527 0.89015572 0.17480033]
  [0.4210606  0.75297824 0.70180338]]]


In [58]:
#Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.18598533 0.91384039 0.32918898 0.77058448 0.84241575]
 [0.07810386 0.6999588  0.5415316  0.3215948  0.21402984]
 [0.08388572 0.92277425 0.99493976 0.01582599 0.49944958]
 [0.23845124 0.71223686 0.6818929  0.92950252 0.31977096]
 [0.13127433 0.96657784 0.2261153  0.68658639 0.82627348]]
Minimum and Maximum Values:
0.0158259917956598 0.9949397640392315


In [59]:
#Write a NumPy program to create a random 10x4 array and extract the first five rows of the # array and store them into a variable.
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[0.80243179 0.81935193 0.07565016 0.37502148]
 [0.51988131 0.56533108 0.12151789 0.93510537]
 [0.62952316 0.92551218 0.34115699 0.05857996]
 [0.46888694 0.33874334 0.22391853 0.33148191]
 [0.61555892 0.45087317 0.99287094 0.13657332]
 [0.01499827 0.38191342 0.80339417 0.42547401]
 [0.51068002 0.44868659 0.32242466 0.53720533]
 [0.34161203 0.84699474 0.28898598 0.31691294]
 [0.65275101 0.96195683 0.028527   0.15761604]
 [0.5250685  0.19564656 0.06610887 0.23612989]]
First 5 rows of the above array:
[[0.80243179 0.81935193 0.07565016 0.37502148]
 [0.51988131 0.56533108 0.12151789 0.93510537]
 [0.62952316 0.92551218 0.34115699 0.05857996]
 [0.46888694 0.33874334 0.22391853 0.33148191]
 [0.61555892 0.45087317 0.99287094 0.13657332]]
First 3 columns of the above array:
[[0.80243179 0.81935193 0.07565016 0.37502148]
 [0.51988131 0.56533108 0.12151789 0.93510537]
 [0.62952316 0.92551218 0.34115699 0.05857996]
 [0.46888694 0.33874334 0.22391853 0.33148191]
 [0.61555892 0.4508

In [60]:
#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).

import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))

[1 6 5 7 2 9 3 0 8 4]
Same result using permutation():
[1 8 3 5 9 2 0 7 4 6]


In [66]:
#Write a NumPy program to create a random integer nos of size 10 and sort it.

import numpy as np
x=np.arange(10)
np.random.randint(x)
print(x)


ValueError: ignored

In [63]:
#Write a NumPy program to create a random integer nos of size 10 and sort it.

import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)


[4 6 1 8 0 5 9 2 7 3]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Write a Pandas program to sort the DataFrame based on country from dataset of 
# movie_metadata.csv

import pandas as pd
import numpy as np
df = pd.read_csv('/home/cyborg/Desktop/Data analytics/programs/movie_metadata.csv')
print("sorted by country")
small_df = df[['num_user_for_reviews','language','country','content_rating','budget','title_year']]
result = small_df.sort_values('country')
print("DataFrame based on release date.")
print(result)

In [ ]:
#Write a Pandas program to display the first 10 rows of the DataFrame.
import pandas as pd
df = pd.read_csv('/home/cyborg/Desktop/Data analytics/programs/movie_metadata.csv')
#Display the first 10 rows
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

In [ ]:
#Write a Pandas program to get the columns of the DataFrame (movies_metadata.csv file).

import pandas as pd
import numpy as np
df = pd.read_csv('movies_metadata.csv')
print("Columns of the DataFrame:")
print(df.columns)

In [ ]:
#Write a Pandas program to get the details of the thrid movie of the DataFrame #(movie_metadata.csv file).

import pandas as pd
df = pd.read_csv('movies_metadata.csv')
third_movie = df.iloc[2]
print("Details of the third moviee:")
print(third_movie)