<a href="https://colab.research.google.com/github/alvas-education-foundation/ISE_3rd_Year_Coding_challenge/blob/master/4AL17IS022_KAVYASHREE_S/Workshop_day_3_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**PANDAS AND NUMPY EXERCISE**

#Write a Pandas program to create and display a one-dimensional array using series  containing  event numbers upto 10000
#tip : use List Comprehension
#ds = pd.Series([0,2, 4, 6, 8..... 10000]) 


In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


#Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and  after convertion print its type 

In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


#Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


#Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
#Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


#Write a Pandas program to convert a NumPy array to a Pandas series. 
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]


In [ ]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


#Write a Pandas program to convert a given Series to an array.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


#Write a Pandas program to sort a given Series.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]


In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


#Write a Pandas program to create a subsets of a given series based on value and condition.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
# value and condtion :  Subset 1 :numbers divisable by 7  Subset 2 : numbers divisable by 5


In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000



In [ ]:
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}


In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


#Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the  array and store them into a variable.

In [4]:
import numpy as np
x = np.random.rand(4, 4)
print("Original array: ")
print(x)
y= x[:2, :]
print("First 2 rows of the above array:")
y= x[:2, :]
print(y)
z= x[:, :3]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[4.32632953e-01 1.66907436e-04 3.04552312e-01 1.59356370e-01]
 [1.62299087e-01 3.09521506e-01 6.82782246e-01 9.81805017e-01]
 [2.91294962e-01 6.65857781e-01 2.97200768e-01 7.17923478e-01]
 [2.91655841e-01 3.02099631e-01 4.18947336e-01 7.53507842e-01]]
First 2 rows of the above array:
[[4.32632953e-01 1.66907436e-04 3.04552312e-01 1.59356370e-01]
 [1.62299087e-01 3.09521506e-01 6.82782246e-01 9.81805017e-01]]
First 3 columns of the above array:
[[4.32632953e-01 1.66907436e-04 3.04552312e-01]
 [1.62299087e-01 3.09521506e-01 6.82782246e-01]
 [2.91294962e-01 6.65857781e-01 2.97200768e-01]
 [2.91655841e-01 3.02099631e-01 4.18947336e-01]]


#Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values

In [3]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.01223115 0.32439082 0.25836017 0.3426531  0.41500567 0.61778691
  0.11376783 0.3648543  0.43348022 0.14553347]
 [0.4766448  0.00478478 0.31896268 0.75132346 0.29852072 0.63155675
  0.4873394  0.69946154 0.12150968 0.34907348]
 [0.98809372 0.88981466 0.42214844 0.26478566 0.05031214 0.26994547
  0.61518023 0.98934844 0.70560824 0.46744846]
 [0.65132941 0.38551494 0.1554512  0.60209363 0.89923961 0.84190264
  0.93728993 0.64114661 0.6343072  0.57546566]
 [0.75833863 0.02090804 0.65647586 0.93444973 0.02290376 0.35570286
  0.17238633 0.56583825 0.53419407 0.21349797]
 [0.01401522 0.60488688 0.19516224 0.65128999 0.69576534 0.32821427
  0.0245487  0.61083871 0.59618003 0.89251075]
 [0.78552054 0.85186606 0.43917413 0.13534716 0.77368781 0.4446248
  0.36882322 0.75183288 0.28098484 0.98271343]
 [0.45359664 0.6459277  0.10391997 0.96813937 0.96246855 0.85618516
  0.14137933 0.88292778 0.21773592 0.54945687]
 [0.13983045 0.83659092 0.46370562 0.10541475 0.12941778 0.918691

#Write a NumPy program to generate 8 random integers between 100 and 300

In [2]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[100 284 273 167 229 226 260 135]


#Write a NumPy program to create a random integer nos of size 20 and sort it

In [1]:
import numpy as np
x=np.arange(20)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[ 1 18  9  4 16 12  7 13 15  3  5  6 17  8 11  0  2 10 19 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
